services:
#    chain_command.example:
#        class: ChainCommandBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    chain_command.command_chain:
        class: ChainCommandBundle\Command\ChainCommand

    chain_command.command_foo:
        class: FooBundle\Command\FooCommand
        tags:
            - {name:chain_command.command}

    chain_command.command_bar:
        class: BarBundle\Command\BarCommand
        tags:
            - {name:chain_command.command}