services:
#    foo.example:
#        class: FooBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    bar.command:
        class: BarBundle\Command\BarCommand

    foo.command:
        class: FooBundle\Command\FooCommand
        calls:
            - [setBar, ['@bar.command']]